### ISSUE TITLE
Wastes memory on macOS 11.6

### ISSUE THREAD

**Issue by mnrkbys** [themittenmac/TrueTree#1]
I'm using TrueTree 0.2 on macOS 11.6
```
% sw_vers 
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
% ./TrueTree --version
0.2
```

In this environment, TrueTree wastes all memory when I run it. In the end, it also wastes disk space due to memory page out.
However, it worked fine on macOS 10.15.7.

There is no other information I can give right now.
What other information do you need in order to fix the bug?

**Comment by mnrkbys** [comment]
I have tested on other macOS versions.
11.2.3 : work
11.3 : not work
11.4 : not work
11.5.2 : not work

**Comment by neomafo88** [comment]
11.6.4: not work

$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.4
BuildVersion:	20G417

$ ./TrueTree --version
0.2

**Comment by jbradley89** [comment]
Apologies for my silence. I'm working on an update for this. The current source uses a call the lsmp executable to obtain mach ports which changed drastically around 11.3. Should have stable updates soon

**Comment by neomafo88** [comment]
> Apologies for my silence. I'm working on an update for this. The current source uses a call the lsmp executable to obtain mach ports which changed drastically around 11.3. Should have stable updates soon

- verified that it works now on MacOS Big Sur v11.6.4
- still seeing a bunch of Deprecation warnings for `GetProcessForPID`, `ProcessInformationCopyDictionary` and `GetProcessPID`
- apparently, it's supposed to be switched to using `NSRunningApplication` nowadays?

**Comment by neomafo88** [comment]
re:obtaining parent PID (PPID) of a given process ID (PID), the following code snippet seems to provide more accurate information vs. the existing getSubmittedPid() in launchdXPC.m:

```
#include <sys/sysctl.h>
#define OPProcessValueUnknown UINT_MAX
int ProcessIDForParentOfProcessID(int pid)
{
  struct kinfo_proc info;
  size_t length = sizeof(struct kinfo_proc);
  int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_PID, pid };
  if (sysctl(mib, 4, &info, &length, NULL, 0) < 0)
    return OPProcessValueUnknown;
  if (length == 0)
    return OPProcessValueUnknown;
  return info.kp_eproc.e_ppid;
}
```

for instance, executing `sudo ./TrueTree within a zsh shell inside Terminal.app`, I would expect the following process parent-child relationship:
...
/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
=> /usr/bin/login
=> /bin/zsh
=> /usr/bin/sudo
=> /path/to/TrueTree

instead, the existing function seems to be displaying:

```
/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
  /bin/zsh
  /path/to/TrueTree
  /usr/bin/login
  /usr/bin/sudo
```

furthermore, logging the result of pid->ppid, parent-of(/path/to/TrueTree) = /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, and prent-of(other processes listed above) = PID=0 (no process name/doesn't appear in listing)

**Comment by jbradley89** [comment]
@neomafo88 Thanks for the info! I hadn't seen that way of getting ppid before. I'd have to perform some tests here to see how this holds up against opening a program via spotlight, dock, etc etc. The reason for the existence of true tree is for the ability to track how different programs were opened instead of just referencing ppid.

You'll notice that if you run  `./TrueTree --standard` you'll get the expected output that you're referring to. This is because it uses only the info from getPPID and ignores the responsible pid and submitted by pid. When building the tree without the --standard switch this is the order in which parents are used if they exist

- Submitted By (launchd_xpc)
- Plist
- Responsible Pid
- PPID

If you want to see which of these pids was used for according parents use

`./TrueTree --sources`
