### ISSUE TITLE
this is the closest to pstree

### ISSUE THREAD

**Issue by orefalo** [themittenmac/TrueTree#10]
this is the closest to a proper pstree,
  it's so difficult to find a decent replacement on osx

yet..

1. an option to remove ugly prefix path on each process (should be the default)
2. an option to remove pid
3. an option to display processes from the parent process (the shell) (should be the default)
4. why only as root?!  why can't I see my current processes as a standard user (per 3)?

a brew script, cause many ppl like me are no xcode experts.

**Comment by x13a** [comment]
> a brew script

https://github.com/Homebrew/homebrew-core/pull/177507

**Comment by orefalo** [comment]
will try when it releases, cheers.
On the original project, the output still looks overly verbage compared to the Linux pstree.

**Comment by jbradley89** [comment]
@x13a I see what you're asking for via the removal of the signing ID. Looks like you closed the PR you had open. I'm working on TrueTree 0.8 at the moment and will have a PR up soon where I will remove the signing info from the Xcode project.  

@orefalo's here long overdue response for you accordingly

1. an option to remove ugly prefix path on each process (should be the default)
-I prefer the full path on macOS. But you're right that an option to show the executable name only should be an option.

2. an option to remove pid
-Agreed. Could also do this.

3. an option to display processes from the parent process (the shell) (should be the default)
-I disagreed with this originally, but over time I have found it more helpful and will make it the default when building the tree. It will be a matter of performing a check to see if ppid != 1 and in such a case the ppid will be used making a more logical tree in many situations such as where a shell is in use under a Terminal.


4. why only as root?! why can't I see my current processes as a standard user (per 3)?
-It must run as root in order to get the enhanced pid information. Sending a privileged message to launchd is required for this and without it you would get a normal process listing which on macOS is next to useless.


I will work on getting a PR out for this in the near future and a release of 0.8.
